_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}

min_steps: 120000
max_steps: 120000

accelerator: gpu
devices: [0]

# mixed precision for extra speed-up
# precision: 16

# perform a validation loop every N training epochs
check_val_every_n_epoch: 1

num_sanity_val_steps: 1 # skip sanity check, because DistillFeature is on a different device than the model before training.

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False

# detect_anomaly: True
