# @package _global_

defaults:
  - _self_
  - data: flute_16000_250.yaml
  - distillation: no_kd.yaml # default.yaml
  - callbacks: no_logger_callbacks.yaml
  - logger: null # set logger here or use command line (e.g. `python train.py logger=tensorboard`)
  - model: wavetable/full_wavetable.yaml #ddsp/small_hpn.yaml
  - task: default.yaml
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"

tags: ["250 fr","16000 sr","eval"]

# teacher checkpoint path for KD evaluation
#model:
# path: "${oc.env:LARGE_GRU_FLUTE_16000_250}"

# passing checkpoint path is necessary for evaluation
ckpt_path: "${oc.env:FULL_WAVETABLE_FLUTE}"

# seed for random number generators in pytorch, numpy and python.random
seed: 42

#logger:
#  wandb:
#    name: "full_wavetable_flute_16000_250_${now:%Y-%m-%d}_${now:%H-%M-%S}"
#    tags: ${tags}
#    group: "decoders"
#  aim:
#    experiment: "audio_generation"

#data:
#  batch_size: 1
