# Jekyll Configuration for Distilling DDSP Supplemental Page

# General settings
title: Distilling DDSP: Exploring Real-Time Audio Generation on Embedded Systems
email: gregorio.giudici@unitn.it
description: >-
  Supplemental materials for the paper "Distilling DDSP: Exploring Real-Time Audio Generation on Embedded Systems," showcasing audio examples, spectrograms, and comparative visualizations.
baseurl: "/distilling-ddsp" # Subpath of your site
url: https://gregogiudici.github.io # Base hostname & protocol for your site

# Author details
author:
  name: Gregorio Giudici
  email: gregorio.giudici@unitn.it
  github: gregogiudici
  twitter: gregogiudici_music # Replace with your actual handle if available

# Theme and plugins
theme: jekyll-theme-modernist # A sleek theme for professional presentations
plugins:
  - jekyll-feed # Generates an Atom feed for the site
  - jekyll-sitemap # Adds a sitemap.xml for better SEO
  - jekyll-seo-tag # Improves meta tags for better visibility
  - jekyll-paginate # Adds pagination for navigation
  - jekyll-include-cache # Enhances rendering speed
markdown: kramdown

# Navigation (Custom for your project)
navigation:
  - title: "Home"
    url: "/"
  - title: "Audio Examples"
    url: "/audio-examples"
  - title: "DDSP Models"
    url: "/ddsp-models"
  - title: "Analysis"
    url: "/analysis"
  - title: "About"
    url: "/about"

# Social sharing options
social:
  twitter_username: gregogiudici_music
  github_username: gregogiudici
  linkedin: gregorio-giudici # Replace with your LinkedIn profile ID if available

# Build settings
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - tmp/

# Search Engine Optimization
jekyll_seo_tag:
  type: Website
  title: "Distilling DDSP: Supplemental Material"
  description: "Explore additional audio and visual resources for DDSP real-time audio generation research."
  url: "https://gregogiudici.github.io/distilling-ddsp"
  author: "Gregorio Giudici"
  twitter:
    card: "summary_large_image"
    site: "@gregogiudici_music"
